In [7]:
def MinMax(dataset):
    MinMax=list()
    for i in range(len(dataset[0])):
        col_value=[row[i] for row in dataset]
        val_min=min(col_value)
        val_max=max(col_value)
        MinMax.append([val_min,val_max])
        return MinMax
    
def normalize(dataset,minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i]=(row[i]-minmax[i][0])/(minmax[i][1]-minmax[i][0])
            
dataset=[[50,30],[20,90]]
print(dataset)
minmax=MinMax(dataset)
print(minmax)
normalize(dataset,minmax)
print(dataset)


[[50, 30], [20, 90]]
[[20, 50]]


IndexError: list index out of range

In [8]:
def MinMax(dataset):
    MinMax=list()
    for i in range(len(dataset[0])):
        col_value=[row[i] for row in dataset]
        val_min=min(col_value)
        val_max=max(col_value)
        MinMax.append([val_min,val_max])
        return MinMax
    
def normalize(dataset,minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i]=(row[i]-minmax[i][0])/(minmax[i][1]-minmax[i][0])
            
dataset=[[50,30],[20,90]]
print(dataset)
minmax=MinMax(dataset)
print(minmax)
normalize(dataset,minmax)
print(dataset)

[[50, 30], [20, 90]]
[[20, 50]]


IndexError: list index out of range

In [9]:
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 
# Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
# Contrive small dataset
dataset = [[50, 30], [20, 90]]
print(dataset)
# Calculate min and max for each column
minmax = dataset_minmax(dataset)
print(minmax)
# Normalize columns
normalize_dataset(dataset, minmax)
print(dataset)

[[50, 30], [20, 90]]
[[20, 50], [30, 90]]
[[1.0, 0.0], [0.0, 1.0]]


In [4]:
from sklearn.preprocessing import Normalizer
X=[[4,1,2,2],[1,3,9,3],[5,7,5,1]]
transformer=Normalizer().fit(X)
transformer
transformer.transform(X)


array([[0.8, 0.2, 0.4, 0.4],
       [0.1, 0.3, 0.9, 0.3],
       [0.5, 0.7, 0.5, 0.1]])

In [9]:
from sklearn.preprocessing import StandardScaler
x=[[0,0],[0,0],[1,1],[1,1]]
scaler=StandardScaler(x)
print(scaler.fit(x))
print(scaler.mean_)
print(scaler.transform(x))
print(scaler.transform([[2,2]]))

StandardScaler(copy=[[0, 0], [0, 0], [1, 1], [1, 1]])
[0.5 0.5]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
[[3. 3.]]


/home/root1/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:67: FutureWarning: Pass copy=[[0, 0], [0, 0], [1, 1], [1, 1]] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [10]:
import numpy as np
dataset = np.array([1.0, 2.0, 3.0, 3.0, 3.0, 2.0, 1.0])
standardized_dataset = (dataset - np.average(dataset)) / (np.std(dataset))
print(standardized_dataset)

[-1.37198868 -0.17149859  1.02899151  1.02899151  1.02899151 -0.17149859
 -1.37198868]


In [11]:
import numpy as np
from sklearn.preprocessing import StandardScaler
dataset = np.array([1.0, 2.0, 3.0, 3.0, 3.0, 2.0, 1.0]).reshape(-1, 1)
scaler = StandardScaler()
scaler.fit(dataset)
standardized_dataset = scaler.transform(dataset)
print(standardized_dataset)
print(np.mean(standardized_dataset))
print(np.std(standardized_dataset))

[[-1.37198868]
 [-0.17149859]
 [ 1.02899151]
 [ 1.02899151]
 [ 1.02899151]
 [-0.17149859]
 [-1.37198868]]
3.172065784643304e-17
1.0
